server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: worksphere-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/worksphere}
    username: ${DATABASE_USERNAME:worksphere_app}
    password: ${DATABASE_PASSWORD:enterprise_secure_pwd_2026}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: WorkSphereHikariPool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: worksphere-hcm-workers
      auto-offset-reset: earliest
    producer:
      acks: all

# Spring Security & JWT
worksphere:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000 # 24 Hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
